-- HITL with native LangGraph: each turn runs on its own checkpoint thread so
-- prior turns don't leak stale messages into the next invocation. The
-- thread_id is generated by `runAgent` and persisted on the pending
-- tool_call row so the confirm/Telegram-callback endpoints can resume the
-- exact thread the interrupt was taken on.
alter table public.tool_calls
  add column if not exists thread_id text;
